---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.dbMigrate.fullName }}
  annotations:
{{ toYaml .Values.dbMigrate.annotations | indent 4 }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.web.serviceAccount.name }}
      containers:
        - name: {{ .Values.dbMigrate.fullName }}
          image: '{{ .Values.image.value }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.value }}
          command: {{ .Values.dbMigrate.command }}
          args: {{ .Values.dbMigrate.args }}
          volumeMounts:
{{ toYaml .Values.common.volumeMounts | indent 12 }}
          env:
          {{- range $keys, $key := .Values.common.secrets }}
          {{- range $secrets, $secret := $key }}
            - name: {{ $secret.env_var }}
              valueFrom:
                secretKeyRef:
                  name: {{ $keys }}
                  key:  {{ $secret.name }}
          {{- end }}
          {{- end }}
      restartPolicy:  {{ .Values.dbMigrate.restartPolicy }}
      securityContext:
        fsGroup: {{ .Values.web.securityContext }}
      volumes:
{{ toYaml .Values.common.volumes | indent 8 }}
  backoffLimit: {{ .Values.dbMigrate.backoffLimit }}
