name: Docker Workflow Example
on: push

jobs:
  container-job:
    runs-on: kmatheny
    # Docker Hub image that `container-job` executes in
    container:
      image: docker:20.10
      env:
        DOCKER_TLS_CERTDIR: /certs
        DOCKER_HOST: dind
      volumes:
        - docker-certs-client-${{ github.run_id }}:/certs/client:ro

    # Service containers to run with `container-job`
    services:
      dind:
        image: docker:22.06-rc-dind
        env:
          DOCKER_TLS_CERTDIR: /certs
        options: >-
          --privileged
        ports:
          - 2376
        volumes:
          - docker-certs-ca-${{ github.run_id }}:/certs/ca
          - docker-certs-client-${{ github.run_id }}:/certs/client

    steps:
      - name: Docker Info
        run: docker info
      - name: Docker Version
        run: docker version
