name: Docker Workflow Example
on: push

jobs:
  container-job:
    runs-on: kmatheny
    # Docker Hub image that `container-job` executes in
    container:
      image: docker:22.06-rc
      env:
        DOCKER_TLS_CERTDIR: /certs
      volumes:
        - docker-certs-client-${{ github.run_id }}:/certs/client:ro

    # Service containers to run with `container-job`
    services:
      dind:
        image: docker:22.06-rc-dind
        env:
          DOCKER_TLS_CERTDIR: /certs
        options: >-
          --privileged
          --network-alias docker
        volumes:
          - docker-certs-ca-${{ github.run_id }}:/certs/ca
          - docker-certs-client-${{ github.run_id }}:/certs/client

    steps:
      - name: Docker Info
        run: docker info
      - name: Docker Version
        run: docker version
