name: Docker Workflow Example
on: push

jobs:
  container-job:
    runs-on: kmatheny
    # Docker Hub image that `container-job` executes in
    container:
      image: docker:20.10
      env:
        DOCKER_HOST: tcp://dind:2376
        DOCKER_TLS_VERIFY: 1
        DOCKER_CERT_PATH: /certs/client
      volumes:
        - docker-certs-client-${{ github.run_id }}:/certs/client:ro

    # Service containers to run with `container-job`
    services:
      dind:
        image: docker:22.06-rc-dind
        env:
          DOCKER_CERT_PATH: /certs
        options: >-
          --privileged
        volumes:
          - docker-certs-ca-${{ github.run_id }}:/certs/ca
          - docker-certs-client-${{ github.run_id }}:/certs/client

    steps:
      - name: Hostname
        run: hostname
      - name: Docker Info
        run: docker info
      - name: Docker Version
        run: docker version
